version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: remove-files.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: shutdown-server.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: start-server.sh
      timeout: 300
      runas: ec2-user