version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn clean install
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - target/*.jar
  - start-server.sh
  - shutdown-server.sh
  - appspec.yml
  discard-paths: yes
